version: "2.4"
services:
  xds:
    build:
      context: ./xds
      dockerfile: ../Dockerfile
    ports:
      - "1800"
  envoy:
    image: envoyproxy/envoy:v1.14.4
    command: ["/usr/local/bin/envoy", "-c /data/bootstrap-xdsv3.yaml", "--drain-time-s 1", "-l debug"]
    volumes:
      - "./envoy-data:/data"
    ports:
      - "8000:80"
      - "9901:9901"
  target:
    image: mendhak/http-https-echo
    scale: 3
    ports:
      - "80"
